dolt.database: "edge_clock"
dolt.host: "doltsrv.lan"
dolt.port: 3307
dolt.user: "root"
backup.enabled: false
dolt.auto-push: false
export.auto: false

sync.remote: "git+ssh://git@github.com/bogorad/edge-clock.git"